[project]
name = "hyperspace"
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115",
    "uvicorn[standard]>=0.49.0",
    "tortoise-orm>=0.21",
    "asyncpg>=0.30",
    "minijinja>=2.20.0",
    "pydantic-settings>=2.0",
    "websockets>=16.0",
    "zstandard>=0.25.0",
    "python-multipart>=0.0.32",
]

[tool.uv]
package = false

[tool.tortoise]
tortoise_orm = "app.config.TORTOISE_ORM"

[tool.prehook]
hooks = [
    "uvx ruff check",
    "uvx ruff format",
]