// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::console_log_type::ConsoleLog;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `console_log`.
///
/// Obtain a handle from the [`ConsoleLogTableAccess::console_log`] method on [`super::RemoteTables`],
/// like `ctx.db.console_log()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.console_log().on_insert(...)`.
pub struct ConsoleLogTableHandle<'ctx> {
    imp: __sdk::TableHandle<ConsoleLog>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `console_log`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConsoleLogTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConsoleLogTableHandle`], which mediates access to the table `console_log`.
    fn console_log(&self) -> ConsoleLogTableHandle<'_>;
}

impl ConsoleLogTableAccess for super::RemoteTables {
    fn console_log(&self) -> ConsoleLogTableHandle<'_> {
        ConsoleLogTableHandle {
            imp: self.imp.get_table::<ConsoleLog>("console_log"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConsoleLogInsertCallbackId(__sdk::CallbackId);
pub struct ConsoleLogDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConsoleLogTableHandle<'ctx> {
    type Row = ConsoleLog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ConsoleLog> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConsoleLogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsoleLogInsertCallbackId {
        ConsoleLogInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConsoleLogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConsoleLogDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsoleLogDeleteCallbackId {
        ConsoleLogDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConsoleLogDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ConsoleLogUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ConsoleLogTableHandle<'ctx> {
    type UpdateCallbackId = ConsoleLogUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ConsoleLogUpdateCallbackId {
        ConsoleLogUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ConsoleLogUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `console_log`,
/// which allows point queries on the field of the same name
/// via the [`ConsoleLogIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.console_log().id().find(...)`.
pub struct ConsoleLogIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ConsoleLog, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConsoleLogTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `console_log`.
    pub fn id(&self) -> ConsoleLogIdUnique<'ctx> {
        ConsoleLogIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConsoleLogIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ConsoleLog> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ConsoleLog>("console_log");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ConsoleLog>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ConsoleLog>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ConsoleLog`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait console_logQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ConsoleLog`.
    fn console_log(&self) -> __sdk::__query_builder::Table<ConsoleLog>;
}

impl console_logQueryTableAccess for __sdk::QueryTableAccessor {
    fn console_log(&self) -> __sdk::__query_builder::Table<ConsoleLog> {
        __sdk::__query_builder::Table::new("console_log")
    }
}
