// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateObjectArgs {
    pub grid_x: i32,
    pub grid_y: i32,
    pub color: String,
}

impl From<CreateObjectArgs> for super::Reducer {
    fn from(args: CreateObjectArgs) -> Self {
        Self::CreateObject {
            grid_x: args.grid_x,
            grid_y: args.grid_y,
            color: args.color,
        }
    }
}

impl __sdk::InModule for CreateObjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_object`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_object {
    /// Request that the remote module invoke the reducer `create_object` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_object:create_object_then`] to run a callback after the reducer completes.
    fn create_object(&self, grid_x: i32, grid_y: i32, color: String) -> __sdk::Result<()> {
        self.create_object_then(grid_x, grid_y, color, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_object` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_object_then(
        &self,
        grid_x: i32,
        grid_y: i32,
        color: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_object for super::RemoteReducers {
    fn create_object_then(
        &self,
        grid_x: i32,
        grid_y: i32,
        color: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateObjectArgs {
                grid_x,
                grid_y,
                color,
            },
            callback,
        )
    }
}
