// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EventKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  get kind() {
    return EventKind;
  },
  identity: __t.identity(),
  brickId: __t.option(__t.u64()).name("brick_id"),
  timestamp: __t.timestamp(),
});
