// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HandlePointerupArgs {
    pub session_id: String,
}

impl From<HandlePointerupArgs> for super::Reducer {
    fn from(args: HandlePointerupArgs) -> Self {
        Self::HandlePointerup {
            session_id: args.session_id,
        }
    }
}

impl __sdk::InModule for HandlePointerupArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `handle_pointerup`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait handle_pointerup {
    /// Request that the remote module invoke the reducer `handle_pointerup` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`handle_pointerup:handle_pointerup_then`] to run a callback after the reducer completes.
    fn handle_pointerup(&self, session_id: String) -> __sdk::Result<()> {
        self.handle_pointerup_then(session_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `handle_pointerup` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn handle_pointerup_then(
        &self,
        session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl handle_pointerup for super::RemoteReducers {
    fn handle_pointerup_then(
        &self,
        session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(HandlePointerupArgs { session_id }, callback)
    }
}
