// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveObjectArgs {
    pub id: u64,
    pub grid_x: i32,
    pub grid_y: i32,
}

impl From<MoveObjectArgs> for super::Reducer {
    fn from(args: MoveObjectArgs) -> Self {
        Self::MoveObject {
            id: args.id,
            grid_x: args.grid_x,
            grid_y: args.grid_y,
        }
    }
}

impl __sdk::InModule for MoveObjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_object`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_object {
    /// Request that the remote module invoke the reducer `move_object` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_object:move_object_then`] to run a callback after the reducer completes.
    fn move_object(&self, id: u64, grid_x: i32, grid_y: i32) -> __sdk::Result<()> {
        self.move_object_then(id, grid_x, grid_y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_object` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_object_then(
        &self,
        id: u64,
        grid_x: i32,
        grid_y: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_object for super::RemoteReducers {
    fn move_object_then(
        &self,
        id: u64,
        grid_x: i32,
        grid_y: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MoveObjectArgs { id, grid_x, grid_y }, callback)
    }
}
