// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SceneObject {
    pub id: u64,
    pub grid_x: i32,
    pub grid_y: i32,
    pub color: String,
}

impl __sdk::InModule for SceneObject {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SceneObject`.
///
/// Provides typed access to columns for query building.
pub struct SceneObjectCols {
    pub id: __sdk::__query_builder::Col<SceneObject, u64>,
    pub grid_x: __sdk::__query_builder::Col<SceneObject, i32>,
    pub grid_y: __sdk::__query_builder::Col<SceneObject, i32>,
    pub color: __sdk::__query_builder::Col<SceneObject, String>,
}

impl __sdk::__query_builder::HasCols for SceneObject {
    type Cols = SceneObjectCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SceneObjectCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            grid_x: __sdk::__query_builder::Col::new(table_name, "grid_x"),
            grid_y: __sdk::__query_builder::Col::new(table_name, "grid_y"),
            color: __sdk::__query_builder::Col::new(table_name, "color"),
        }
    }
}

/// Indexed column accessor struct for the table `SceneObject`.
///
/// Provides typed access to indexed columns for query building.
pub struct SceneObjectIxCols {
    pub id: __sdk::__query_builder::IxCol<SceneObject, u64>,
}

impl __sdk::__query_builder::HasIxCols for SceneObject {
    type IxCols = SceneObjectIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SceneObjectIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SceneObject {}
