// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::scene_object_type::SceneObject;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `scene_object`.
///
/// Obtain a handle from the [`SceneObjectTableAccess::scene_object`] method on [`super::RemoteTables`],
/// like `ctx.db.scene_object()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.scene_object().on_insert(...)`.
pub struct SceneObjectTableHandle<'ctx> {
    imp: __sdk::TableHandle<SceneObject>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `scene_object`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SceneObjectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SceneObjectTableHandle`], which mediates access to the table `scene_object`.
    fn scene_object(&self) -> SceneObjectTableHandle<'_>;
}

impl SceneObjectTableAccess for super::RemoteTables {
    fn scene_object(&self) -> SceneObjectTableHandle<'_> {
        SceneObjectTableHandle {
            imp: self.imp.get_table::<SceneObject>("scene_object"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SceneObjectInsertCallbackId(__sdk::CallbackId);
pub struct SceneObjectDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SceneObjectTableHandle<'ctx> {
    type Row = SceneObject;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SceneObject> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SceneObjectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SceneObjectInsertCallbackId {
        SceneObjectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SceneObjectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SceneObjectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SceneObjectDeleteCallbackId {
        SceneObjectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SceneObjectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SceneObjectUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SceneObjectTableHandle<'ctx> {
    type UpdateCallbackId = SceneObjectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SceneObjectUpdateCallbackId {
        SceneObjectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SceneObjectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `scene_object`,
/// which allows point queries on the field of the same name
/// via the [`SceneObjectIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.scene_object().id().find(...)`.
pub struct SceneObjectIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SceneObject, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SceneObjectTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `scene_object`.
    pub fn id(&self) -> SceneObjectIdUnique<'ctx> {
        SceneObjectIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SceneObjectIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SceneObject> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SceneObject>("scene_object");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SceneObject>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SceneObject>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SceneObject`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait scene_objectQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SceneObject`.
    fn scene_object(&self) -> __sdk::__query_builder::Table<SceneObject>;
}

impl scene_objectQueryTableAccess for __sdk::QueryTableAccessor {
    fn scene_object(&self) -> __sdk::__query_builder::Table<SceneObject> {
        __sdk::__query_builder::Table::new("scene_object")
    }
}
