// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetColorArgs {
    pub session_id: String,
    pub color: String,
}

impl From<SetColorArgs> for super::Reducer {
    fn from(args: SetColorArgs) -> Self {
        Self::SetColor {
            session_id: args.session_id,
            color: args.color,
        }
    }
}

impl __sdk::InModule for SetColorArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_color`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_color {
    /// Request that the remote module invoke the reducer `set_color` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_color:set_color_then`] to run a callback after the reducer completes.
    fn set_color(&self, session_id: String, color: String) -> __sdk::Result<()> {
        self.set_color_then(session_id, color, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_color` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_color_then(
        &self,
        session_id: String,
        color: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_color for super::RemoteReducers {
    fn set_color_then(
        &self,
        session_id: String,
        color: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetColorArgs { session_id, color }, callback)
    }
}
