// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Brick = __t.object("Brick", {
  id: __t.u64(),
  get position() {
    return Position;
  },
  get color() {
    return Color;
  },
  draggedBy: __t.option(__t.identity()),
});
export type Brick = __Infer<typeof Brick>;

// The tagged union or sum type for the algebraic type `Color`.
export const Color = __t.enum("Color", {
  Cyan: __t.unit(),
  Purple: __t.unit(),
  Orange: __t.unit(),
  Green: __t.unit(),
  Pink: __t.unit(),
  Yellow: __t.unit(),
});
export type Color = __Infer<typeof Color>;

export const Cursor = __t.object("Cursor", {
  identity: __t.identity(),
  get position() {
    return Position;
  },
});
export type Cursor = __Infer<typeof Cursor>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  get kind() {
    return EventKind;
  },
  identity: __t.identity(),
  brickId: __t.option(__t.u64()),
  timestamp: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

// The tagged union or sum type for the algebraic type `EventKind`.
export const EventKind = __t.enum("EventKind", {
  UserConnected: __t.unit(),
  UserDisconnected: __t.unit(),
  BrickCreated: __t.unit(),
  BrickDeleted: __t.unit(),
  DragStarted: __t.unit(),
  DragEnded: __t.unit(),
});
export type EventKind = __Infer<typeof EventKind>;

export const HtmlBroadcast = __t.object("HtmlBroadcast", {
  identity: __t.identity(),
  html: __t.string(),
});
export type HtmlBroadcast = __Infer<typeof HtmlBroadcast>;

export const Position = __t.object("Position", {
  x: __t.i32(),
  y: __t.i32(),
  z: __t.i32(),
});
export type Position = __Infer<typeof Position>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  get color() {
    return Color;
  },
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

