// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_info_type::UserInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_info`.
///
/// Obtain a handle from the [`UserInfoTableAccess::user_info`] method on [`super::RemoteTables`],
/// like `ctx.db.user_info()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_info().on_insert(...)`.
pub struct UserInfoTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_info`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserInfoTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserInfoTableHandle`], which mediates access to the table `user_info`.
    fn user_info(&self) -> UserInfoTableHandle<'_>;
}

impl UserInfoTableAccess for super::RemoteTables {
    fn user_info(&self) -> UserInfoTableHandle<'_> {
        UserInfoTableHandle {
            imp: self.imp.get_table::<UserInfo>("user_info"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserInfoInsertCallbackId(__sdk::CallbackId);
pub struct UserInfoDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserInfoTableHandle<'ctx> {
    type Row = UserInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserInfoInsertCallbackId {
        UserInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserInfoDeleteCallbackId {
        UserInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserInfoUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserInfoTableHandle<'ctx> {
    type UpdateCallbackId = UserInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserInfoUpdateCallbackId {
        UserInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `session_id` unique index on the table `user_info`,
/// which allows point queries on the field of the same name
/// via the [`UserInfoSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_info().session_id().find(...)`.
pub struct UserInfoSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserInfo, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserInfoTableHandle<'ctx> {
    /// Get a handle on the `session_id` unique index on the table `user_info`.
    pub fn session_id(&self) -> UserInfoSessionIdUnique<'ctx> {
        UserInfoSessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserInfoSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `session_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserInfo> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserInfo>("user_info");
    _table.add_unique_constraint::<String>("session_id", |row| &row.session_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserInfo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserInfo`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_infoQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserInfo`.
    fn user_info(&self) -> __sdk::__query_builder::Table<UserInfo>;
}

impl user_infoQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_info(&self) -> __sdk::__query_builder::Table<UserInfo> {
        __sdk::__query_builder::Table::new("user_info")
    }
}
