// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_cursor_type::UserCursor;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_cursor`.
///
/// Obtain a handle from the [`UserCursorTableAccess::user_cursor`] method on [`super::RemoteTables`],
/// like `ctx.db.user_cursor()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_cursor().on_insert(...)`.
pub struct UserCursorTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserCursor>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_cursor`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserCursorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserCursorTableHandle`], which mediates access to the table `user_cursor`.
    fn user_cursor(&self) -> UserCursorTableHandle<'_>;
}

impl UserCursorTableAccess for super::RemoteTables {
    fn user_cursor(&self) -> UserCursorTableHandle<'_> {
        UserCursorTableHandle {
            imp: self.imp.get_table::<UserCursor>("user_cursor"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserCursorInsertCallbackId(__sdk::CallbackId);
pub struct UserCursorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserCursorTableHandle<'ctx> {
    type Row = UserCursor;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserCursor> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserCursorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserCursorInsertCallbackId {
        UserCursorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserCursorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserCursorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserCursorDeleteCallbackId {
        UserCursorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserCursorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserCursorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserCursorTableHandle<'ctx> {
    type UpdateCallbackId = UserCursorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserCursorUpdateCallbackId {
        UserCursorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserCursorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `user_cursor`,
/// which allows point queries on the field of the same name
/// via the [`UserCursorIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_cursor().identity().find(...)`.
pub struct UserCursorIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserCursor, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserCursorTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `user_cursor`.
    pub fn identity(&self) -> UserCursorIdentityUnique<'ctx> {
        UserCursorIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserCursorIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<UserCursor> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserCursor>("user_cursor");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserCursor>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserCursor>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserCursor`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_cursorQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserCursor`.
    fn user_cursor(&self) -> __sdk::__query_builder::Table<UserCursor>;
}

impl user_cursorQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_cursor(&self) -> __sdk::__query_builder::Table<UserCursor> {
        __sdk::__query_builder::Table::new("user_cursor")
    }
}
