// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as IndexProcedure from "../index_procedure";

export type IndexArgs = __Infer<typeof IndexProcedure.params>;
export type IndexResult = __Infer<typeof IndexProcedure.returnType>;

