// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateBrickReducer from "../create_brick_reducer";
import DeleteBrickReducer from "../delete_brick_reducer";
import EndDragReducer from "../end_drag_reducer";
import MoveBrickReducer from "../move_brick_reducer";
import SetColorReducer from "../set_color_reducer";
import SetNameReducer from "../set_name_reducer";
import StartDragReducer from "../start_drag_reducer";
import UpdateCursorReducer from "../update_cursor_reducer";

export type CreateBrickParams = __Infer<typeof CreateBrickReducer>;
export type DeleteBrickParams = __Infer<typeof DeleteBrickReducer>;
export type EndDragParams = __Infer<typeof EndDragReducer>;
export type MoveBrickParams = __Infer<typeof MoveBrickReducer>;
export type SetColorParams = __Infer<typeof SetColorReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type StartDragParams = __Infer<typeof StartDragReducer>;
export type UpdateCursorParams = __Infer<typeof UpdateCursorReducer>;

